rogue-thi-app/styles/Imprint.module.css
Take a look at it and tell me your opinion.
=> (fixed): Size of imprint headings

rogue-thi-app/styles/Imprint.module.css
Simplified imprint style code and made the text more responsive
=> style: simplified imprint style

package-lock.json, rogue-thi-app/pages/calendar.js
I filtered the examList to only show the real exams.
Also the exam dates are now sorted chronically.
=> filtered and sorted exam dates

rogue-thi-app/pages/calendar.js
Rerequest to merge this fork with the develop branch.
=> Removed THI Events from Events Tab in Appointment Page

rogue-thi-app/pages/food.js
First Implemenation of the Issue #110
=> First Implementation of a better filter for the food page

rogue-thi-app/pages/food.js
Just slight improvement of the UI
=> Improved Foodfilter UI

rogue-thi-app/lib/date-utils.js, rogue-thi-app/pages/timetable.js
=> Show the next week in the timetable if the current day is a sunday

rogue-thi-app/components/modal/PersonalizeModal.js, rogue-thi-app/data/clubs.json, rogue-thi-app/lib/hooks/dashboard.js, rogue-thi-app/pages/index.js, rogue-thi-app/pages/personal.js
This pullrequest adds a togglable attribute to ALL_DASHBOARD_CARDS so that you cannot disable the PersonalCard. Issue: #186 
Also it includes the new Clubs "Nightlife Neuburg" and "Studenten bilden Schüler". Issue: #185
=> Fixed PersonalPage and Clubs Problems

rogue-thi-app/lib/date-utils.js, rogue-thi-app/pages/food.js, rogue-thi-app/styles/Mensa.module.css
Implemented a Version of the mentioned Food Tab in Issue #183.
Until we get further data from Reimanns or Mensa this is the best we could do.
=> Implemented a version of the Food Tab.

rogue-thi-app/pages/personal.js
Changes:
- Fixes bug, where MyTHI is also displayed for students 
- Adds the ability to tap the Bib and Matr. number to be copied
- Makes the logout button dynamic. For guests "Login" with the correct icon is now displayed.
Links with Issue #182  and PR #187
=> Improves Personal Page

rogue-thi-app/pages/imprint.js, rogue-thi-app/pages/personal.js
- Re-enables imprint.js (fixes #201)
- Removes outdated privacy policy
- Updates outdated repo link
- Removes intrusive copy icons
=> Re-enables imprint.js

rogue-thi-app/pages/personal.js
Prevents the full reload of the app on link click. Also the Capacitor App crashes.
=> fixes wrong routing

rogue-thi-app/components/cards/FoodCard.js, rogue-thi-app/package.json, rogue-thi-app/pages/personal.js
- The Mensa card did not work on empty days (e.g. Sunday) because todayEntries was undefined after filtering and so the following sorting failed. Therefore, a new constant was introduced.
- Another incorrect routing was identified and fixed for the personal page.
- Updated the npm scripts for the Capacitor app, as they previously did not render the CSS.
=> Bug fixes (Mensa Card, Personal)

rogue-thi-app/pages/personal.js
- simplified conditional access 
- added fixed string with comma
- hide average if isNaN
=> Hide NaN average grades 

rogue-thi-app/components/allCards.js, rogue-thi-app/components/cards/RoomCard.js, rogue-thi-app/lib/backend-utils/rooms-utils.js
The room card shows:
- suitable rooms based on the next gap in the timetable
- prioritizes rooms in same building and same floor
- only buildings in Ingolstadt and vice versa
=> 🪄 Suggest rooms based on timetable in room card

rogue-thi-app/components/SwipeableTabs.js, rogue-thi-app/lib/backend-utils/food-utils.js, rogue-thi-app/lib/date-utils.js, rogue-thi-app/pages/food.js, rogue-thi-app/styles/Mensa.module.css
Implements the design suggested by @Robert27 in #225 
Shows days without data:
Fill days not provided by the API:
=> 🪲 Wrong display of current week in food.js #225

rogue-thi-app/pages/api/reimanns.js
I updated the API to correctly display the current prices.
=> Fixes reimanns prices

rogue-thi-app/styles/Home.module.css, rogue-thi-app/styles/Mensa.module.css, rogue-thi-app/styles/Mobility.module.css
Improves card colors for better readability
=> ♿️ improve card colors

rogue-thi-app/lib/date-utils.jsx
=> Fix date format using slashes instead of dots

.github/workflows/test.yml, CONTRIBUTING.md, rogue-thi-app/.prettierignore, rogue-thi-app/.prettierrc, rogue-thi-app/components/RoomMap.jsx, rogue-thi-app/package.json, rogue-thi-app/pages/food/[...mealId].jsx
- adds Prettier code style check on push
=> 🎨 adds Prettier Github action

rogue-thi-app/pages/timetable.jsx
=> Fixes #348

rogue-thi-app/components/RoomMap.jsx, rogue-thi-app/components/cards/FoodCard.jsx, rogue-thi-app/components/modal/DashboardModal.jsx, rogue-thi-app/components/modal/FilterFoodModal.jsx, rogue-thi-app/components/modal/LanguageModal.jsx, rogue-thi-app/components/modal/PersonalDataModal.jsx, rogue-thi-app/components/modal/ThemeModal.jsx, rogue-thi-app/lib/backend-utils/food-utils.js, rogue-thi-app/lib/providers/DashboardProvider.jsx, rogue-thi-app/lib/providers/FoodFilterProvider.jsx, rogue-thi-app/lib/providers/ModalProvider.jsx, rogue-thi-app/lib/providers/StyleProvider.jsx, rogue-thi-app/lib/providers/ThemeProvider.jsx, rogue-thi-app/pages/_app.jsx, rogue-thi-app/pages/food/[...mealId].jsx, rogue-thi-app/pages/food/index.jsx, rogue-thi-app/pages/index.jsx, rogue-thi-app/pages/personal.jsx
- restructures the providers into own components
- replace useContext with individual hooks
- fix small food bug
=> 🎨 restructure providers

rogue-thi-app/lib/date-utils.js, rogue-thi-app/pages/api/cl-events.js, rogue-thi-app/pages/events.jsx, rogue-thi-app/styles/Calendar.module.css
- update events UI
- show event location if approved by organizer
- (only show year if shown date is not current year)
=> ✨ show event locations and update UI

.vscode/extensions.json, .vscode/i18n-ally-custom-framework.yml, .vscode/settings.json, rogue-thi-app/public/locales/de/dashboard.json, rogue-thi-app/public/locales/en/dashboard.json
Adds inline translations for i18n using i18n-ally. @Robert27
=> 🧑‍💻 add i18n-ally

rogue-thi-app/capacitor.config.json, rogue-thi-app/components/map/AttributionControl.jsx, rogue-thi-app/pages/rooms/index.jsx, rogue-thi-app/pages/rooms/search.jsx
=> 🐛 fix room highlights
